name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: actions/checkout@v2
    - uses: darrenjennings/algolia-docsearch-action@master
      with:
        algolia_application_id: 'RA3RRQUBO1'
        algolia_api_key: '5fc4b9cbb86b1510fd966ce24afb13a4'
        file: 'algolia/my-algolia-config.json'
