name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#     - uses: actions/checkout@v2
#     - uses: darrenjennings/algolia-docsearch-action@master
#       with:
#         algolia_application_id: 'RA3RRQUBO1'
#         algolia_api_key: '5fc4b9cbb86b1510fd966ce24afb13a4'
#         file: 'https://gist.github.com/devanshdixit/412b013be6eb6910f6563ad789366bfb'
    - name: Push indices to Algolia
      uses: signcl/docsearch-scraper-action@master
      env:
       APPLICATION_ID: 'RA3RRQUBO1'
       API_KEY: '5fc4b9cbb86b1510fd966ce24afb13a4'
       CONFIG: '{"index_name": "docs","start_urls": ["https://docs.greatexpectations.io/docs/"],"sitemap_alternate_links": true,"stop_urls": [],"selectors": {"lvl1": "header h1","lvl2": "article h2","lvl3": "article h3","lvl4": "article h4","lvl5": "article h5, article td:first-child","lvl6": "article h6","text": "article p, article li, article td:last-child"},"strip_chars": " .,;:#","custom_settings": {"separatorsToIndex": "_","attributesForFaceting": ["language","version","type","docusaurus_tag"],"attributesToRetrieve": ["hierarchy","content","anchor","url","url_without_anchor","type"]}}'
